version: '3'
services:
  app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    depends_on:
      - db
    environment:
      DB_HOST: mysql://db:3306
    ports:
      - "3000:3000"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /api
    command: node index.js
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
  db:
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: 'nwsmaterials'
        MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db-data: