version: '3'
services:
  app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    depends_on:
      - db
    environment:
      DB_HOST: mysql://db:3306
    ports:
      - "3000:3000"
    networks:
      - frontend  
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node index.js'
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - backend
      - frontend  
  db:
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: 'nwsmaterials'
        MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend: