version: '3'
services:
  db:
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    image: mysql:8
    #command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: 'enzo'
        MYSQL_PASSWORD: 'herichard'
        MYSQL_DATABASE: 'nwsmaterials'
        MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: "/usr/bin/mysql --user=enzo --password=herichard --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: 
      context: .
      target: app
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: mysql://db:3306
    ports:
      - "3000:3000"
  api:
    build:
      context: .
      target: api
    working_dir: /api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
volumes:
  db-data: