on: [push]

name: Build & test

jobs:
  build-docker:
      needs: Test
      runs-on: ubuntu-latest
      steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push to GitHub registry api
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: ghcr.io/enzoherichard/api
            target: api
        - name: Build and push to GitHub registry app
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: ghcr.io/enzoherichard/app
            target: app
#  Test:
#       name: Npm run test docker
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v3
#         - run: docker-compose down -v
#         - run: docker-compose up -d --build
#         - run: docker exec api npm run test
#         - run: docker-compose down